# 무작정 Numpy 따라해보기

import

In [7]:
import numpy as np

np.array([1,2,3])


array([1, 2, 3])

Numpy는 행과 열로 나누어져 있는데 행열을 구분하는것은 중괄호( [ ] )로 구분이 가능하다.
만약 2 * 2 행렬을 만들고 싶다면  
([1,2],[3,4])  
이런 식으로 중괄호로 하나의 행을 구성하고 구분자로 , 이후 다시 중괄호로 2번째 행을 구성해 주면 되는 방식이다.


  
  
## CSV 파일 활용

In [48]:
f = open('iris.csv')

data=[]

head = f.readline()
head = head.strip().split(',')
print(head)
print(head[:4])


['sepal.length', 'sepal.width', 'petal.length', 'petal.width', 'variety']
['sepal.length', 'sepal.width', 'petal.length', 'petal.width']


In [49]:
for line in f:
    i= line.strip().split(',')
    for x in range(4):
        i[x] = float(i[x])
    data.append(i)
"""

    if i[4] == '"Setosa"':       # 판다에서 apply api를 사용하면 일괄 변경이 가능해 보임
        i[4] = 0
    elif i[4] == '"Versicolor"':
        i[4] = 1
    else:
        i[4] = 2
"""
   
f.close()

In [50]:
data

[[5.1, 3.5, 1.4, 0.2, 'Setosa'],
 [4.9, 3.0, 1.4, 0.2, 'Setosa'],
 [4.7, 3.2, 1.3, 0.2, 'Setosa'],
 [4.6, 3.1, 1.5, 0.2, 'Setosa'],
 [5.0, 3.6, 1.4, 0.2, 'Setosa'],
 [5.4, 3.9, 1.7, 0.4, 'Setosa'],
 [4.6, 3.4, 1.4, 0.3, 'Setosa'],
 [5.0, 3.4, 1.5, 0.2, 'Setosa'],
 [4.4, 2.9, 1.4, 0.2, 'Setosa'],
 [4.9, 3.1, 1.5, 0.1, 'Setosa'],
 [5.4, 3.7, 1.5, 0.2, 'Setosa'],
 [4.8, 3.4, 1.6, 0.2, 'Setosa'],
 [4.8, 3.0, 1.4, 0.1, 'Setosa'],
 [4.3, 3.0, 1.1, 0.1, 'Setosa'],
 [5.8, 4.0, 1.2, 0.2, 'Setosa'],
 [5.7, 4.4, 1.5, 0.4, 'Setosa'],
 [5.4, 3.9, 1.3, 0.4, 'Setosa'],
 [5.1, 3.5, 1.4, 0.3, 'Setosa'],
 [5.7, 3.8, 1.7, 0.3, 'Setosa'],
 [5.1, 3.8, 1.5, 0.3, 'Setosa'],
 [5.4, 3.4, 1.7, 0.2, 'Setosa'],
 [5.1, 3.7, 1.5, 0.4, 'Setosa'],
 [4.6, 3.6, 1.0, 0.2, 'Setosa'],
 [5.1, 3.3, 1.7, 0.5, 'Setosa'],
 [4.8, 3.4, 1.9, 0.2, 'Setosa'],
 [5.0, 3.0, 1.6, 0.2, 'Setosa'],
 [5.0, 3.4, 1.6, 0.4, 'Setosa'],
 [5.2, 3.5, 1.5, 0.2, 'Setosa'],
 [5.2, 3.4, 1.4, 0.2, 'Setosa'],
 [4.7, 3.2, 1.6, 0.2, 'Setosa'],
 [4.8, 3.1

In [51]:
iris = np.array(data)
iris

array([['5.1', '3.5', '1.4', '0.2', 'Setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'Setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'Setosa'],
       ['5.4', '3.9', '1.7', '0.4', 'Setosa'],
       ['4.6', '3.4', '1.4', '0.3', 'Setosa'],
       ['5.0', '3.4', '1.5', '0.2', 'Setosa'],
       ['4.4', '2.9', '1.4', '0.2', 'Setosa'],
       ['4.9', '3.1', '1.5', '0.1', 'Setosa'],
       ['5.4', '3.7', '1.5', '0.2', 'Setosa'],
       ['4.8', '3.4', '1.6', '0.2', 'Setosa'],
       ['4.8', '3.0', '1.4', '0.1', 'Setosa'],
       ['4.3', '3.0', '1.1', '0.1', 'Setosa'],
       ['5.8', '4.0', '1.2', '0.2', 'Setosa'],
       ['5.7', '4.4', '1.5', '0.4', 'Setosa'],
       ['5.4', '3.9', '1.3', '0.4', 'Setosa'],
       ['5.1', '3.5', '1.4', '0.3', 'Setosa'],
       ['5.7', '3.8', '1.7', '0.3', 'Setosa'],
       ['5.1', '3.8', '1.5', '0.3', 'Setosa'],
       ['5.4', '3.4', '1.7', '0.2', 'Setosa'],
       ['5.1'

In [59]:
iris=np.where(iris == 'Setosa', 0, iris)
iris=np.where(iris == 'Versicolor', 1, iris)
iris=np.where(iris == 'Virginica', 2, iris)
iris=iris.astype(np.float64)
iris

<ipython-input-59-27b042fa1bb4>:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  iris=np.where(iris == 'Setosa', 0, iris)
<ipython-input-59-27b042fa1bb4>:2: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  iris=np.where(iris == 'Versicolor', 1, iris)
<ipython-input-59-27b042fa1bb4>:3: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  iris=np.where(iris == 'Virginica', 2, iris)


array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3

In [62]:
type(iris), len(iris), iris.shape, iris.dtype

(numpy.ndarray, 150, (150, 5), dtype('float64'))

In [63]:
iris > 5

array([[ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, Fal

In [64]:
iris.sum()

2228.7

In [65]:
iris[10]

array([5.4, 3.7, 1.5, 0.2, 0. ])

In [66]:
iris[:,0]

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [67]:
iris[:5]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ]])

In [68]:
iris[:]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3

In [72]:
iris[:10,[0,2,3]]

array([[5.1, 1.4, 0.2],
       [4.9, 1.4, 0.2],
       [4.7, 1.3, 0.2],
       [4.6, 1.5, 0.2],
       [5. , 1.4, 0.2],
       [5.4, 1.7, 0.4],
       [4.6, 1.4, 0.3],
       [5. , 1.5, 0.2],
       [4.4, 1.4, 0.2],
       [4.9, 1.5, 0.1]])

In [74]:
setosa=iris[iris[:,4]==0]
setosa

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3

In [75]:
setosa.shape

(50, 5)

In [76]:
versicolor = iris[iris[:,4]==1]
versicolor

array([[7. , 3.2, 4.7, 1.4, 1. ],
       [6.4, 3.2, 4.5, 1.5, 1. ],
       [6.9, 3.1, 4.9, 1.5, 1. ],
       [5.5, 2.3, 4. , 1.3, 1. ],
       [6.5, 2.8, 4.6, 1.5, 1. ],
       [5.7, 2.8, 4.5, 1.3, 1. ],
       [6.3, 3.3, 4.7, 1.6, 1. ],
       [4.9, 2.4, 3.3, 1. , 1. ],
       [6.6, 2.9, 4.6, 1.3, 1. ],
       [5.2, 2.7, 3.9, 1.4, 1. ],
       [5. , 2. , 3.5, 1. , 1. ],
       [5.9, 3. , 4.2, 1.5, 1. ],
       [6. , 2.2, 4. , 1. , 1. ],
       [6.1, 2.9, 4.7, 1.4, 1. ],
       [5.6, 2.9, 3.6, 1.3, 1. ],
       [6.7, 3.1, 4.4, 1.4, 1. ],
       [5.6, 3. , 4.5, 1.5, 1. ],
       [5.8, 2.7, 4.1, 1. , 1. ],
       [6.2, 2.2, 4.5, 1.5, 1. ],
       [5.6, 2.5, 3.9, 1.1, 1. ],
       [5.9, 3.2, 4.8, 1.8, 1. ],
       [6.1, 2.8, 4. , 1.3, 1. ],
       [6.3, 2.5, 4.9, 1.5, 1. ],
       [6.1, 2.8, 4.7, 1.2, 1. ],
       [6.4, 2.9, 4.3, 1.3, 1. ],
       [6.6, 3. , 4.4, 1.4, 1. ],
       [6.8, 2.8, 4.8, 1.4, 1. ],
       [6.7, 3. , 5. , 1.7, 1. ],
       [6. , 2.9, 4.5, 1.5, 1. ],
       [5.7, 2

In [77]:
versicolor.shape

(50, 5)